In [7]:
import numpy as np

**PROBLEM 1**

In [4]:
A = np.array( [ [3,-1,4],[1,5,-9] ] )
B = np.array( [ [2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3] ] )

In [5]:
result1 = np.dot(A,B)
result2 = A @ B
print(result1)
print(result2)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]
[[ 37  14 -32 -10]
 [-54  -7  58  65]]


**PROBLEM 2**

In [27]:
A = np.array( [ [3,1,4],[1,5,9],[-5,3,1] ] )
#result = -(A*A*A) + 9*(A*A) - 15*A
#result = -A**3 + 9*A**2 - 15*A
result = -(A @ A @ A) + 9*(A @ A) - 15*A
print(result)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


**PROBLEM 3**

In [14]:
A = np.ones((7,7))
A = np.triu(A)
print(A)

[[1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [17]:
B = np.ones((7,7))
B = np.triu(B)*6
B = B - 1
print(B)

[[ 5.  5.  5.  5.  5.  5.  5.]
 [-1.  5.  5.  5.  5.  5.  5.]
 [-1. -1.  5.  5.  5.  5.  5.]
 [-1. -1. -1.  5.  5.  5.  5.]
 [-1. -1. -1. -1.  5.  5.  5.]
 [-1. -1. -1. -1. -1.  5.  5.]
 [-1. -1. -1. -1. -1. -1.  5.]]


In [18]:
result = A @ B @ A

[[ -1.   4.  15.  32.  55.  84. 119.]
 [ -6.  -6.   0.  12.  30.  54.  84.]
 [ -5. -10.  -9.  -2.  11.  30.  55.]
 [ -4.  -8. -12. -10.  -2.  12.  32.]
 [ -3.  -6.  -9. -12.  -9.   0.  15.]
 [ -2.  -4.  -6.  -8. -10.  -6.   4.]
 [ -1.  -2.  -3.  -4.  -5.  -6.  -1.]]


In [24]:
result = result.astype(np.int64)
#result.dtype
print(result)

[[ -1   4  15  32  55  84 119]
 [ -6  -6   0  12  30  54  84]
 [ -5 -10  -9  -2  11  30  55]
 [ -4  -8 -12 -10  -2  12  32]
 [ -3  -6  -9 -12  -9   0  15]
 [ -2  -4  -6  -8 -10  -6   4]
 [ -1  -2  -3  -4  -5  -6  -1]]


**PROBLEM 4**

In [43]:
def my_func(array_in):
    A = array_in
    negative = A < 0 
    result = A
    result[negative] = 0
    
    return result

In [44]:
A = np.array( [ [3,-1,4],[1,5,-9] ] )
print(my_func(A))

[[3 0 4]
 [1 5 0]]


**PROBLEM 5**

In [47]:
A = np.arange(6).reshape((3,2))
A = A.T
print(A)

[[0 2 4]
 [1 3 5]]


In [48]:
B = np.ones((3,3))
B = np.triu(B)*3
B = B.T
print(B)

[[3. 0. 0.]
 [3. 3. 0.]
 [3. 3. 3.]]


In [52]:
C = np.eye(3)*-2
print(C)

[[-2. -0. -0.]
 [-0. -2. -0.]
 [-0. -0. -2.]]


In [67]:
result1 = np.column_stack((np.zeros((3,4)), A.T, np.eye(3)))
print(result1)

[[0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 2. 3. 0. 1. 0.]
 [0. 0. 0. 0. 4. 5. 0. 0. 1.]]


In [66]:
result2 = np.column_stack((A,np.zeros((2,3)), np.zeros((2,3))))
print(result2)

[[0. 2. 4. 0. 0. 0. 0. 0. 0.]
 [1. 3. 5. 0. 0. 0. 0. 0. 0.]]


In [64]:
result3 = np.column_stack((B,np.zeros((3,3)), C))
print(result3)

[[ 3.  0.  0.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0.  0.  0. -0. -0. -2.]]


In [68]:
result = np.vstack((result1,result2,result3))
print(result)

[[ 0.  0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0.  0.  0. -0. -0. -2.]]


**PROBLEM 6**

In [108]:
def row_stoch(array_in):
    sums = array_in.sum(axis=1)
    fin = array_in / sums.reshape((len(sums),1))
       
    return fin

In [109]:
A = np.array( [ [3,1,4],[1,5,9] ] )
result = row_stoch(A)
print(result)

[[0.375      0.125      0.5       ]
 [0.06666667 0.33333333 0.6       ]]


**PROBLEM 7**

In [97]:
grid = np.load("grid.npy")
print(grid)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 33 67 46 55 12 32 63 93

In [98]:
#to the right
np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])

48477312

In [102]:
#to the left (logically the same, as horizontal too)
#np.max(grid[:,3:] * grid[:,2:-1] * grid[:,1:-2] * grid[:,:-3])

48477312

In [105]:
#vertically
np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])

51267216

In [106]:
#diagonal
np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])

40304286